version: 2.1

jobs:
  preconditions:
    docker: &BUILDIMAGE
      - image: jenkinsrise/cci-v2-components:0.0.4
    steps:
      - checkout
      - run: git log --no-decorate --format=oneline | head -50
      - run: git log --no-decorate --grep='^Merge pull request' --format=oneline | head -1 | cut -d' ' -f 1


workflows:
  workflow1:
    jobs:
      - preconditions
